# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-10 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_order', mezzanine.core.fields.OrderField(null=True, verbose_name='Order')),
                ('image', mezzanine.core.fields.FileField(max_length=200, verbose_name='File')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Description')),
                ('description_tr', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('description_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('description_ar', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Caption')),
                ('caption_tr', models.CharField(blank=True, max_length=200, null=True, verbose_name='Caption')),
                ('caption_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Caption')),
                ('caption_ar', models.CharField(blank=True, max_length=200, null=True, verbose_name='Caption')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('site', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'ordering': ['_order'],
                'verbose_name': 'Slide',
                'verbose_name_plural': 'Slides',
            },
        ),
    ]
