# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-10 20:15
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=mezzanine.core.fields.FileField(max_length=200, verbose_name='Image'),
        ),
    ]
