# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-25 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('announcements', '0002_auto_20170524_1851'),
        ('pages', '0008_auto_20170524_1917'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portlet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords_string', models.CharField(blank=True, editable=False, max_length=500)),
                ('language', models.CharField(default='', editable=False, max_length=5)),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('slug', models.CharField(blank=True, help_text='Leave blank to have the URL auto-generated from the title.', max_length=2000, null=True, verbose_name='URL')),
                ('_meta_title', models.CharField(blank=True, help_text='Optional title to be used in the HTML title tag. If left blank, the main title field will be used.', max_length=500, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('gen_description', models.BooleanField(default=True, help_text='If checked, the description will be automatically generated from content. Uncheck if you want to manually set a custom description.', verbose_name='Generate description')),
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Draft'), (2, 'Published')], default=2, help_text='With Draft chosen, will only be shown for admin users on the site.', verbose_name='Status')),
                ('publish_date', models.DateTimeField(blank=True, db_index=True, help_text="With Published chosen, won't be shown until this time", null=True, verbose_name='Published from')),
                ('expiry_date', models.DateTimeField(blank=True, help_text="With Published chosen, won't be shown after this time", null=True, verbose_name='Expires on')),
                ('short_url', models.URLField(blank=True, null=True)),
                ('in_sitemap', models.BooleanField(default=True, verbose_name='Show in sitemap')),
                ('content_model', models.CharField(editable=False, max_length=50, null=True)),
                ('slot', models.CharField(choices=[(b'ana-sayfa', 'Ana Sayfa'), (b'sag', 'Sa\u011f'), (b'sol', 'Sol'), (b'alt', 'Alt'), (b'menu-alti', 'Menu Alt\u0131'), (b'menu-ustu', 'Menu \xdcst\xfc')], max_length=10, verbose_name='Yer')),
                ('order', models.PositiveSmallIntegerField(default=999, verbose_name='S\u0131ra')),
                ('css_classes', models.CharField(blank=True, default=b'col-md-12', max_length=100)),
                ('header_css_classes', models.CharField(blank=True, help_text='Ba\u015fl\u0131\u011f\u0131 gizlemek i\xe7in hidden ekleyiniz', max_length=100)),
                ('body_css_classes', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ('order',),
                'verbose_name': 'mod\xfcl',
                'verbose_name_plural': 'mod\xfcller',
            },
        ),
        migrations.CreateModel(
            name='AnnouncementPortlet',
            fields=[
                ('portlet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portlets.Portlet')),
                ('show_thumbnail', models.BooleanField(default=False, verbose_name='Resimleri G\xf6ster')),
                ('count', models.IntegerField(default=10, verbose_name='say\u0131')),
                ('height', models.PositiveSmallIntegerField(default=250, verbose_name='Y\xfckseklik')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='announcements.AnnouncementCategory', verbose_name='kategori')),
            ],
            options={
                'verbose_name': 'Duyuru Mod\xfcl\xfc',
                'verbose_name_plural': 'Duyuru Mod\xfclleri',
            },
            bases=('portlets.portlet',),
        ),
        migrations.CreateModel(
            name='DialogPortlet',
            fields=[
                ('portlet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portlets.Portlet')),
                ('content', mezzanine.core.fields.RichTextField(verbose_name='Content')),
                ('width', models.PositiveIntegerField(default=400, verbose_name='Geni\u015flik')),
                ('timeout', models.PositiveIntegerField(default=30, help_text='Mesaj bir defa g\xf6sterildikten ka\xe7 dakika sonra tekrar g\xf6sterilsin?', verbose_name='Zaman A\u015f\u0131m\u0131')),
            ],
            options={
                'verbose_name': 'dialog mod\xfcl\xfc',
                'verbose_name_plural': 'dialog mod\xfclleri',
            },
            bases=('portlets.portlet', models.Model),
        ),
        migrations.CreateModel(
            name='MenuPortlet',
            fields=[
                ('portlet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portlets.Portlet')),
                ('template', models.CharField(blank=True, choices=[(b'portlets/menu_portlet.html', '\xd6n Tan\u0131ml\u0131'), (b'portlets/menu_portlet_small.html', 'K\xfc\xe7\xfck \u0130kon'), (b'portlets/menu_portlet_alt.html', 'Alt Menu'), (b'portlets/menu_portlet_box.html', 'Resimli Kutu')], max_length=100, null=True, verbose_name=b'Tema dosyas\xc4\xb1')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Page', verbose_name='Men\xfc')),
            ],
            options={
                'verbose_name': 'men\xfc mod\xfcl\xfc',
                'verbose_name_plural': 'men\xfc mod\xfclleri',
            },
            bases=('portlets.portlet',),
        ),
        migrations.CreateModel(
            name='PagePortlet',
            fields=[
                ('portlet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portlets.Portlet')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Page', verbose_name='Sayfa')),
            ],
            options={
                'verbose_name': 'sayfa mod\xfcl\xfc',
                'verbose_name_plural': 'sayfa mod\xfclleri',
            },
            bases=('portlets.portlet',),
        ),
        migrations.CreateModel(
            name='SlideShowPortlet',
            fields=[
                ('portlet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portlets.Portlet')),
                ('size', models.CharField(blank=True, choices=[(b'big', '800x0'), (b'normal', '500x0'), (b'billboard-l', '950x250 - Resim merkezden k\u0131rp\u0131l\u0131r.'), (b'billboard-m', '700x300 - Resim merkezden k\u0131rp\u0131l\u0131r.'), (b'billboard-mm', '700x319 - Resim merkezden k\u0131rp\u0131l\u0131r.'), (b'billboard-s', '400x300 - Resim merkezden k\u0131rp\u0131l\u0131r.'), (b'billboard-xs', '250x354 - Afi\u015fler i\xe7in bu se\xe7ene\u011fi kullan\u0131n\u0131z.'), (b'small-xs', '150x50')], max_length=30, null=True, verbose_name='Boyut')),
                ('js_option', models.CharField(blank=True, choices=[(b'nivoSlider', b'Nivo Slider'), (b'bxslider', b'BxSlider'), (b'bs-carousel', b'Boostrap Carousel')], help_text='Kullanmak istedi\u011finiz javascript k\xfct\xfcphanesini se\xe7tikten sonra ilgili k\xfct\xfcphanenin se\xe7eneklerini d\xfczenleyiniz', max_length=15, null=True, verbose_name='Kullan\u0131lacak Javascript K\xfct\xfcphanesi')),
                ('theme', models.CharField(blank=True, choices=[(b'theme-default', b'Default'), (b'theme-light', b'A\xc3\xa7\xc4\xb1k Tema 1'), (b'theme-light2', b'A\xc3\xa7\xc4\xb1k Tema 2'), (b'theme-dark', b'Koyu Tema 1')], max_length=30, null=True, verbose_name='Tema')),
                ('mode', models.CharField(blank=True, choices=[(b'horizontal', b'horizontal (yatay)'), (b'vertical', b'vertical (dikey)'), (b'fade', b'fade')], max_length=10, null=True, verbose_name='Mod')),
                ('pager', models.BooleanField(default=False, verbose_name='Sayfalay\u0131c\u0131')),
                ('auto', models.BooleanField(default=True, verbose_name='Auto Start')),
                ('captions', models.BooleanField(default=True, verbose_name='Resim Ba\u015fl\u0131klar\u0131n\u0131 G\xf6ster')),
                ('carouselMode', models.BooleanField(default=False, verbose_name="Bir slide'de birden fazla resim olsun")),
                ('maxSlides', models.PositiveSmallIntegerField(default=3, verbose_name='Maksimum Slide say\u0131s\u0131')),
                ('minSlides', models.PositiveSmallIntegerField(default=2, verbose_name='Minimum Slide Say\u0131s\u0131(k\xfc\xe7\xfck ekranlar i\xe7in)')),
                ('slideWidth', models.PositiveSmallIntegerField(default=315, verbose_name='Slide geni\u015fli\u011fi')),
                ('moveSlides', models.PositiveSmallIntegerField(default=1, editable=False)),
            ],
            options={
                'verbose_name': 'Slideshow Mod\xfcl\xfc',
                'verbose_name_plural': 'slideshow mod\xfclleri',
            },
            bases=('portlets.portlet',),
        ),
        migrations.CreateModel(
            name='TextPortlet',
            fields=[
                ('portlet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portlets.Portlet')),
                ('content', mezzanine.core.fields.RichTextField(verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Metin Mod\xfcl\xfc',
                'verbose_name_plural': 'Metin Mod\xfclleri',
            },
            bases=('portlets.portlet', models.Model),
        ),
        migrations.AddField(
            model_name='portlet',
            name='site',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
    ]
