# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-18 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portlet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords_string', models.CharField(blank=True, editable=False, max_length=500)),
                ('language', models.CharField(default='', editable=False, max_length=5)),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('slug', models.CharField(blank=True, help_text='Leave blank to have the URL auto-generated from the title.', max_length=2000, null=True, verbose_name='URL')),
                ('_meta_title', models.CharField(blank=True, help_text='Optional title to be used in the HTML title tag. If left blank, the main title field will be used.', max_length=500, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('gen_description', models.BooleanField(default=True, help_text='If checked, the description will be automatically generated from content. Uncheck if you want to manually set a custom description.', verbose_name='Generate description')),
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Draft'), (2, 'Published')], default=2, help_text='With Draft chosen, will only be shown for admin users on the site.', verbose_name='Status')),
                ('publish_date', models.DateTimeField(blank=True, db_index=True, help_text="With Published chosen, won't be shown until this time", null=True, verbose_name='Published from')),
                ('expiry_date', models.DateTimeField(blank=True, help_text="With Published chosen, won't be shown after this time", null=True, verbose_name='Expires on')),
                ('short_url', models.URLField(blank=True, null=True)),
                ('in_sitemap', models.BooleanField(default=True, verbose_name='Show in sitemap')),
                ('slot', models.CharField(choices=[(b'ana-sayfa', 'Ana Sayfa'), (b'sag', 'Sa\u011f'), (b'sol', 'Sol'), (b'alt', 'Alt'), (b'menu-alti', 'Menu Alt\u0131'), (b'menu-ustu', 'Menu \xdcst\xfc')], max_length=10, verbose_name='Yer')),
                ('order', models.PositiveSmallIntegerField(default=999, verbose_name='S\u0131ra')),
                ('css_classes', models.CharField(blank=True, default=b'col-md-12', max_length=100)),
                ('header_css_classes', models.CharField(blank=True, help_text='Ba\u015fl\u0131\u011f\u0131 gizlemek i\xe7in hidden ekleyiniz', max_length=100)),
                ('body_css_classes', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ('order',),
                'verbose_name': 'mod\xfcl',
                'verbose_name_plural': 'mod\xfcller',
            },
        ),
        migrations.CreateModel(
            name='TextPortlet',
            fields=[
                ('portlet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portlets.Portlet')),
                ('content', mezzanine.core.fields.RichTextField(verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Metin Mod\xfcl\xfc',
                'verbose_name_plural': 'Metin Mod\xfclleri',
            },
            bases=('portlets.portlet', models.Model),
        ),
        migrations.AddField(
            model_name='portlet',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_portlets.portlet_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='portlet',
            name='site',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
    ]
