# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-30 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20150527_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='language',
            field=models.CharField(default='tr', editable=False, max_length=5),
        ),
    ]
