# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-06 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_page_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='language',
            field=models.CharField(default='', editable=False, max_length=5),
        ),
    ]
