# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-24 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20170506_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='image',
            field=mezzanine.core.fields.FileField(blank=True, max_length=255, verbose_name='Page Image'),
        ),
        migrations.AddField(
            model_name='page',
            name='subtitle',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Alt Ba\u015fl\u0131k'),
        ),
    ]
