# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-24 19:17
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20170524_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='featured_image',
            field=mezzanine.core.fields.FileField(blank=True, max_length=255, verbose_name='Featured Image'),
        ),
    ]
