# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-24 18:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ('-publish_date',), 'verbose_name': 'Duyuru', 'verbose_name_plural': 'Duyurular'},
        ),
        migrations.AlterModelOptions(
            name='announcementcategory',
            options={'ordering': ('title',), 'verbose_name': 'Kategori', 'verbose_name_plural': 'Kategoriler'},
        ),
    ]
