# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-07 22:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20170607_2147'),
        ('flatpages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatPageIndex',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flatpages.FlatPageCategory')),
            ],
            options={
                'ordering': ('_order',),
                'verbose_name': 'Kategori Index',
                'verbose_name_plural': 'Kategori Index Sayfalar\u0131',
            },
            bases=('pages.page',),
        ),
    ]
