# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-18 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('user', 'User'), ('list', 'List'), ('search', 'Search')], max_length=10, verbose_name='Type')),
                ('value', models.CharField(max_length=140, verbose_name='Value')),
                ('interested', models.BooleanField(default=True, verbose_name='Interested')),
            ],
            options={
                'ordering': ('-id',),
                'verbose_name': 'Twitter query',
                'verbose_name_plural': 'Twitter queries',
            },
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_id', models.CharField(max_length=50, verbose_name='Twitter ID')),
                ('created_at', models.DateTimeField(null=True, verbose_name='Date/time')),
                ('text', models.TextField(null=True, verbose_name='Message')),
                ('profile_image_url', models.URLField(null=True, verbose_name='Profile image URL')),
                ('user_name', models.CharField(max_length=100, null=True, verbose_name='User name')),
                ('full_name', models.CharField(max_length=100, null=True, verbose_name='Full name')),
                ('retweeter_profile_image_url', models.URLField(null=True, verbose_name='Profile image URL (Retweeted by)')),
                ('retweeter_user_name', models.CharField(max_length=100, null=True, verbose_name='User name (Retweeted by)')),
                ('retweeter_full_name', models.CharField(max_length=100, null=True, verbose_name='Full name (Retweeted by)')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to='twitter.Query')),
            ],
            options={
                'ordering': ('-created_at',),
                'verbose_name': 'Tweet',
                'verbose_name_plural': 'Tweets',
            },
        ),
    ]
